/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jkurapati.grocery.api;

import com.google.common.flogger.FluentLogger;
import com.jkurapati.grocery.api.server.JettyServer;

import static com.google.common.flogger.StackSize.FULL;
import static java.util.logging.Level.SEVERE;

public class App {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    public static void main(String[] args) {
        try {
            new JettyServer().startRestEasyServer();
        } catch (Exception e) {
            logger.at(SEVERE).withStackTrace(FULL).withCause(e).log("Error starting server");
        }
    }
}
