/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jkurapati.grocery.api;

import com.google.common.flogger.FluentLogger;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.jkurapati.grocery.api.server.ConfigModule;
import com.jkurapati.grocery.api.server.JettyModule;
import org.eclipse.jetty.server.Server;

import static com.google.common.flogger.StackSize.FULL;
import static java.util.logging.Level.SEVERE;

public class App {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    public static void main(String[] args) {
        try {
            final Injector injector = Guice.createInjector(new ConfigModule(args), new JettyModule());
            Server server = injector.getInstance(Server.class);
            server.start();
            server.join();
        } catch (Exception e) {
            logger.at(SEVERE).withStackTrace(FULL).withCause(e).log("Error starting server");
        }
    }
}
